### ISSUE TITLE
Problem with example code

### ISSUE THREAD

**Issue by dagarou** [adafruit/Adafruit_CircuitPython_BLE_Apple_Media#10]
When trying to execute the code from [Adafruit_CircuitPython_BLE_Apple_Media#usage-example](https://github.com/adafruit/Adafruit_CircuitPython_BLE_Apple_Media#usage-example) Python throws an error:

`Traceback (most recent call last):
  File "playertest.py", line 16, in <module>
    radio.start_advertising(a)
  File "/usr/local/lib/python3.7/dist-packages/adafruit_ble/__init__.py", line 195, in start_advertising
    timeout=0 if timeout is None else timeout,
  File "/usr/local/lib/python3.7/dist-packages/_bleio/adapter_.py", line 200, in start_advertising
    raise NotImplementedError("Advertising not implemented")
NotImplementedError: Advertising not implemented
`

Searching in Google the only thing I found was someone with the same problem
https://www.raspberrypi.org/forums/viewtopic.php?t=286085#p1823321

**Comment by tannewt** [comment]
Blinka bleio doesn't support the peripheral role (having something initiate the connection to the device) which is what advertising is part of.

I opened https://github.com/adafruit/Adafruit_Blinka_bleio/issues/34 to track this.
